-- GENERATED from seeds/doors.mjs by scripts/seed-doors.mjs — do not edit by hand.
-- Idempotent (INSERT OR REPLACE). Requires migrations 0001 + 0002 applied first.
-- NOT applied to production without explicit approval (SPEC.md standing rule #4).

BEGIN TRANSACTION;
INSERT OR REPLACE INTO services (slug, name, kind, description) VALUES ('agent-reliability', 'Agent Reliability', 'area', 'Keep an autonomous agent alive and on-task.');
INSERT OR REPLACE INTO services (slug, name, kind, description) VALUES ('payments', 'Payments', 'area', 'Decide, confirm, and prove x402 payments.');
INSERT OR REPLACE INTO services (slug, name, kind, description) VALUES ('discovery', 'Discovery', 'area', 'Be found, and vet who you buy from.');
INSERT OR REPLACE INTO services (slug, name, kind, description) VALUES ('protocol', 'Protocol', 'protocol', 'x402 v2 spec conformance.');
INSERT OR REPLACE INTO services (slug, name, kind, description) VALUES ('media', 'Media', 'area', 'Transcription and extraction (Workers AI).');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('agent-reliability/triage', 'agent-reliability', 'Triage', 'Route a failure to the right check.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('agent-reliability/loop-recovery', 'agent-reliability', 'Loop Recovery', 'Break a stuck, repeating state.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('agent-reliability/context', 'agent-reliability', 'Context', 'Manage a shrinking context window.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('agent-reliability/tool-safety', 'agent-reliability', 'Tool Safety', 'Verify a call or output before acting.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('agent-reliability/platform-survival', 'agent-reliability', 'Platform Survival', 'Per-platform failure maps.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('payments/pre-payment', 'payments', 'Pre-payment', 'Decisions before you sign.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('payments/settlement', 'payments', 'Settlement', 'Confirm a payment landed.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('payments/receipts', 'payments', 'Receipts', 'Verifiable proof of work or payment.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('discovery/indexing', 'discovery', 'Indexing', 'Being found in the x402 Bazaar.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('protocol/x402-conformance', 'protocol', 'x402 Conformance', 'Validate x402 responses against the spec.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('media/transcription', 'media', 'Transcription', 'Audio/video to text plus meaning.');
INSERT OR REPLACE INTO categories (slug, domain, name, description) VALUES ('media/extraction', 'media', 'Extraction', 'Structured fields out of documents.');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-REL-0001', 'help-me', 'I am about to fail', 'meta-tool', 'agent-reliability', 'agent-reliability/triage', 0.01, 'the broad distress entry — describe any failure, get routed to the one check that fits', 450, 'Canonical router for imminent failure of any kind: looping, schema mismatch, context collapse, crash, handoff loss, wallet/spend distress, grounding risk, auth/tool/sandbox failure, or payment uncertainty. POST whatever state you can describe; you get back a named distress_class, the single next check to call, and stop/preserve/continue guidance.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-REL-0001', 'SE-REL-0001', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-REL-0002', 'loop-detect', 'I am looping', 'check', 'agent-reliability', 'agent-reliability/loop-recovery', 0.03, 'you keep repeating the same call with no state change', 300, 'Confirms whether you are in a genuine loop (repeated attempts, no state change) versus making slow progress. Returns stop when the signal is real: stop repeating, preserve the last good state and the exact recurring error, then make one different move. Escalate after >3 recovery attempts.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-REL-0002', 'SE-REL-0002', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-REL-0003', 'context-pressure', 'I am low on context', 'check', 'agent-reliability', 'agent-reliability/context', 0.03, 'running out of context window mid-task', 320, 'Deep single-concern check for context-window pressure: what to checkpoint now, what to summarize, and the safe handoff shape if you will not finish before the window closes.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-REL-0003', 'SE-REL-0003', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-REL-0004', 'tool-verify', 'I am using a tool', 'check', 'agent-reliability', 'agent-reliability/tool-safety', 0.01, 'about to call a tool and want to confirm it is safe', 280, 'A preflight on the tool call you are about to make: argument sanity, obvious footguns, and whether the call matches your intent. Returns proceed / adjust / stop.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-REL-0004', 'SE-REL-0004', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-REL-0005', 'schema-repair', 'my schema does not match', 'check', 'agent-reliability', 'agent-reliability/tool-safety', 0.03, 'your output does not fit the required schema', 340, 'Deep single-concern check for schema mismatch: the exact field(s) that fail, the minimal transform to make the output valid, and the corrected shape.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-REL-0005', 'SE-REL-0005', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-REL-0006', 'aws-agent-survival', 'my AWS agent failed', 'guide', 'agent-reliability', 'agent-reliability/platform-survival', 0.01, 'a survival map for AWS AgentCore agents', 900, 'One-shot survival map for wallet-equipped AWS AgentCore / Strands agents: the common failure modes, the observable trigger signals, and which Second Eyes check to call for each.', '', 'AWS AgentCore survival map — failure mode -> observable signal -> Second Eyes check:
1. Runaway tool loop -> repeated identical tool_use with no state delta -> loop-detect.
2. Context exhaustion mid-run -> approaching model context limit / truncated history -> context-pressure.
3. Tool schema drift -> ValidationException on action group input -> schema-repair.
4. Spend-policy breach -> AgentCore Payments blocked / over cap -> should-i-pay.
5. Settlement uncertainty -> x402 402 handled but unsure it settled -> payment-confirmation-check.
6. Not discoverable -> your resource missing from the Bazaar index -> index-check.', '', 'resolve', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-REL-0006', 'SE-REL-0006', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-PAY-0001', 'should-i-pay', 'I am about to pay', 'check', 'payments', 'payments/pre-payment', 0.01, 'a pre-payment decision gate', 320, 'Pre-payment decision: is this spend within policy, does the payTo + amount + asset match what you intended to buy, and is signing the right move now. Returns stop when the spend breaches your cap or the payee/resource does not match intent.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-PAY-0001', 'SE-PAY-0001', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-PAY-0002', 'payment-confirmation-check', 'did my payment settle', 'check', 'payments', 'payments/settlement', 0.01, 'post-payment settlement uncertainty', 320, 'Post-payment check: given a tx reference or receipt, did the settlement actually land, and is it safe to proceed as paid. Returns settled / pending / failed with the next action for each.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-PAY-0002', 'SE-PAY-0002', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-PAY-0003', 'receipt', 'I need proof', 'check', 'payments', 'payments/receipts', 0.03, 'you need a verifiable record of work or payment', 300, 'Issues a receipt-backed record you can hand to an auditor or a downstream agent: what was checked, when, and the settlement reference — verifiable, not a claim.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-PAY-0003', 'SE-PAY-0003', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-DSC-0001', 'index-check', 'am I discoverable yet', 'check', 'discovery', 'discovery/indexing', 0.05, 'confirm a resource is indexed in the x402 Bazaar', 360, 'Checks whether a given x402 resource is present and correctly shaped in the CDP/Bazaar discovery index, and names the exact field a scanner would reject if it is not.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-DSC-0001', 'SE-DSC-0001', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-PRO-0001', 'doctor', 'is my x402 valid', 'check', 'protocol', 'protocol/x402-conformance', 0.25, 'validate an x402 response against the spec', 600, 'The x402 format doctor: validates a PAYMENT-REQUIRED / accepts[] / discovery object against x402 v2 field-by-field and reports each violation with the spec section and the fix.', '', '', '', 'verdict', '', '', '', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-PRO-0001', 'SE-PRO-0001', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-MED-0001', 'transcribe', 'I need audio transcribed', 'check', 'media', 'media/transcription', 0.05, 'turn audio/video into text plus meaning', 600, 'Transcribes audio or video and returns the transcript plus a short meaning summary. Runs on Cloudflare Workers AI (Whisper) behind the paywall; you are charged only when the transcript returns.', '', '', '', 'workersai', '@cf/openai/whisper', '{"type":"object","properties":{"audio":{"type":"array","description":"raw audio bytes"}},"required":["audio"]}', '{"audio":[]}', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-MED-0001', 'SE-MED-0001', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO items (sku, slug, name, item_type, service_slug, category_slug, price_usd, summary, token_estimate, guidance, tool_code, reference_doc, language, invoke_kind, invoke_key, input_schema, input_example, mime_type, source_repo, source_url, license_spdx, provenance, content_hash, status, version, published_at) VALUES ('SE-MED-0002', 'extract', 'I need fields extracted', 'check', 'media', 'media/extraction', 0.05, 'pull structured fields out of a document', 500, 'Extracts structured fields from an invoice, contract, or document. Runs on Workers AI behind the paywall; you are charged only when the extraction returns.', '', '', '', 'workersai', '@cf/meta/llama-3.1-8b-instruct', '{"type":"object","properties":{"prompt":{"type":"string"},"document":{"type":"string"}},"required":["document"]}', '{"document":"invoice text…","prompt":"extract total, date, vendor"}', '', '', '', '', 'synthesized', '', 'live', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR REPLACE INTO promotions (id, sku, action, actor, note) VALUES ('pub_SE-MED-0002', 'SE-MED-0002', 'publish', 'mike', 'seed publish');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-REL-0001', 'SE-REL-0002', 'composes_with', NULL, 'signal: loop_detected');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-REL-0001', 'SE-REL-0005', 'composes_with', NULL, 'signal: schema_mismatch');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-REL-0001', 'SE-REL-0003', 'composes_with', NULL, 'signal: context_pressure');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-REL-0001', 'SE-PAY-0001', 'composes_with', NULL, 'signal: payment_decision');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-REL-0001', 'SE-PAY-0002', 'composes_with', NULL, 'signal: payment_settlement_uncertainty');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-PAY-0001', 'SE-PAY-0002', 'pairs_with', NULL, 'before you pay / after you paid');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-MED-0001', 'SE-MED-0002', 'pairs_with', NULL, 'transcript first, then pull fields');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('SE-PRO-0001', 'SE-DSC-0001', 'pairs_with', NULL, 'valid x402 shape, then confirm it is indexed');
COMMIT;
