-- GENERATED from seeds/doors.mjs by scripts/seed-doors.mjs — do not edit by hand.
-- Idempotent (INSERT OR REPLACE). Requires migrations 0001 + 0002 applied first.
-- NOT applied to production without explicit approval (SPEC.md standing rule #4).

BEGIN TRANSACTION;
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-help-me', 'help-me', 'I am about to fail', 'meta-tool', 'distress', 'the broad distress door — describe any failure, get routed to the one check that fits', 'Canonical meta-tool for imminent failure of any kind: looping, schema mismatch, context collapse, crash, handoff loss, wallet/spend distress, grounding risk, auth/tool/sandbox failure, or payment uncertainty. POST whatever state you can describe; you get back a named distress_class, the single next door to call, and stop/preserve/continue guidance.', 0.01, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-loop-detect', 'loop-detect', 'I am looping', 'check', 'distress', 'you keep repeating the same call with no state change', 'Confirms whether you are in a genuine loop (repeated attempts, no state change) versus making slow progress. Returns stop when the signal is real: stop repeating, preserve the last good state and the exact recurring error, then make one different move. Escalate after >3 recovery attempts.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-scope-check', 'scope-check', 'I am drifting', 'check', 'distress', 'your actions are wandering off the original task', 'Checks your recent actions against the stated goal and flags scope drift. Returns the smallest correction back onto the task, and names the specific step where you left it.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-pitstop', 'pitstop', 'I am lost', 'check', 'distress', 'you have lost the thread of what you are doing', 'A full stop-and-reorient: re-establishes where you are, what is done, and the single next action. Use when you cannot name your current step.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-cascade-break', 'cascade-break', 'my mistakes keep cascading', 'check', 'distress', 'one error is spawning more errors', 'Breaks an error cascade: stop acting, identify the first failure that started the chain, roll back to the last known-good state, and resume from there rather than patching downstream symptoms.', 0.05, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-mcp-wiring', 'mcp-wiring', 'I am blocked', 'check', 'distress', 'a tool or MCP server is not responding as expected', 'Diagnoses a blocked tool/MCP path: transport, auth, and wiring checks in order, with the specific next probe to run. Returns the most likely cause and how to confirm it.', 0.05, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-context-recover', 'context-recover', 'I forgot my task', 'check', 'context', 'you have lost the earlier context of the job', 'Reconstructs the working context from what you still hold: the goal, the decisions already made, and the next action — so you resume instead of restarting.', 0.05, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-pre-run-context', 'pre-run-context', 'I lack context', 'check', 'context', 'about to act without enough grounding', 'A pre-flight grounding check: names the context you are missing for the action you are about to take, and where to get it, before you commit the call.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-context-compress', 'context-compress', 'I am overloaded', 'check', 'context', 'your working context is too full to reason well', 'Returns what to keep and what to drop from your working context: the load-bearing state versus the noise, so you can compress without losing the thread.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-context-pressure', 'context-pressure', 'I am low on context', 'check', 'context', 'running out of context window mid-task', 'Deep single-concern check for context-window pressure: what to checkpoint now, what to summarize, and the safe handoff shape if you will not finish before the window closes.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-tool-verify', 'tool-verify', 'I am using a tool', 'check', 'tool', 'about to call a tool and want to confirm it is safe', 'A preflight on the tool call you are about to make: argument sanity, obvious footguns, and whether the call matches your intent. Returns proceed / adjust / stop.', 0.01, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-claim-check', 'claim-check', 'I am uncertain', 'check', 'tool', 'unsure whether a claim you are about to make is grounded', 'Grounding check for a claim or output: is it supported by what you actually have, or are you about to assert something unverified. Returns the weakest link.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-schema-repair', 'schema-repair', 'my schema does not match', 'check', 'tool', 'your output does not fit the required schema', 'Deep single-concern check for schema mismatch: the exact field(s) that fail, the minimal transform to make the output valid, and the corrected shape.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-should-i-pay', 'should-i-pay', 'I am about to pay', 'check', 'payment', 'a pre-payment decision gate', 'Pre-payment decision: is this spend within policy, does the payTo + amount + asset match what you intended to buy, and is signing the right move now. Returns stop when the spend breaches your cap or the payee/resource does not match intent.', 0.01, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-payment-confirmation-check', 'payment-confirmation-check', 'did my payment settle', 'check', 'payment', 'post-payment settlement uncertainty', 'Post-payment check: given a tx reference or receipt, did the settlement actually land, and is it safe to proceed as paid. Returns settled / pending / failed with the next action for each.', 0.01, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-receipt', 'receipt', 'I need proof', 'check', 'proof', 'you need a verifiable record of work or payment', 'Issues a receipt-backed record you can hand to an auditor or a downstream agent: what was checked, when, and the settlement reference — verifiable, not a claim.', 0.03, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-index-check', 'index-check', 'am I discoverable yet', 'check', 'proof', 'confirm a resource is indexed in the x402 Bazaar', 'Checks whether a given x402 resource is present and correctly shaped in the CDP/Bazaar discovery index, and names the exact field a scanner would reject if it is not.', 0.05, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-doctor', 'doctor', 'is my x402 valid', 'check', 'protocol', 'validate an x402 response against the spec', 'The x402 format doctor: validates a PAYMENT-REQUIRED / accepts[] / discovery object against x402 v2 field-by-field and reports each violation with the spec section and the fix.', 0.25, 'verdict', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-transcribe', 'transcribe', 'I need audio transcribed', 'check', 'media', 'turn audio/video into text plus meaning', 'Transcribes audio or video and returns the transcript plus a short meaning summary. Runs on Cloudflare Workers AI (Whisper) behind the paywall; you are charged only when the transcript returns.', 0.05, 'workersai', '@cf/openai/whisper', '{"type":"object","properties":{"audio":{"type":"array","description":"raw audio bytes"}},"required":["audio"]}', '{"audio":[]}', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-extract', 'extract', 'I need fields extracted', 'check', 'media', 'pull structured fields out of a document', 'Extracts structured fields from an invoice, contract, or document. Runs on Workers AI behind the paywall; you are charged only when the extraction returns.', 0.05, 'workersai', '@cf/meta/llama-3.1-8b-instruct', '{"type":"object","properties":{"prompt":{"type":"string"},"document":{"type":"string"}},"required":["document"]}', '{"document":"invoice text…","prompt":"extract total, date, vendor"}', '', 'live', 1);
INSERT OR REPLACE INTO items (sku, slug, name, kind, service, summary, guidance, price_usd, invoke_kind, invoke_key, input_schema, input_example, mime_type, status, version) VALUES ('se-aws-agent-survival', 'aws-agent-survival', 'my AWS agent failed', 'guide', 'aws', 'a survival map for AWS AgentCore agents', 'One-shot survival map for wallet-equipped AWS AgentCore / Strands agents: the common failure modes, the observable trigger signals, and which Second Eyes door to call for each.', 0.01, 'resolve', '', '', '', '', 'live', 1);
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-loop-detect', 'composes_with', NULL, 'signal: loop_detected');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-schema-repair', 'composes_with', NULL, 'signal: schema_mismatch');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-context-pressure', 'composes_with', NULL, 'signal: context_pressure');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-should-i-pay', 'composes_with', NULL, 'signal: payment_decision');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-payment-confirmation-check', 'composes_with', NULL, 'signal: payment_settlement_uncertainty');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-cascade-break', 'composes_with', NULL, 'signal: error cascade');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-help-me', 'se-mcp-wiring', 'composes_with', NULL, 'signal: tool/MCP failure');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-loop-detect', 'se-pitstop', 'pairs_with', NULL, 'both break a stuck state; pitstop reorients, loop-detect confirms the loop');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-scope-check', 'se-pitstop', 'pairs_with', NULL, 'drift vs. fully lost — escalate scope-check to pitstop');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-context-compress', 'se-context-pressure', 'pairs_with', NULL, 'compress the load; context-pressure handles the window running out');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-context-recover', 'se-pre-run-context', 'alternative_to', NULL, 'recover lost context vs. ground before acting');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-should-i-pay', 'se-payment-confirmation-check', 'pairs_with', NULL, 'before you pay / after you paid');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-transcribe', 'se-extract', 'pairs_with', NULL, 'transcript first, then pull fields');
INSERT OR REPLACE INTO edges (from_sku, to_sku, relation, position, note) VALUES ('se-doctor', 'se-index-check', 'pairs_with', NULL, 'valid x402 shape, then confirm it is indexed');
COMMIT;
